### ISSUE TITLE
Missing dependency: S4Vectors

### ISSUE THREAD

**Issue by timcadman** [isglobal-brge/dsExposomeClient#18]
When running:

`ds.invExWAS("exposome_object", phenotype =  "blood_pre", covariables = "sex")`

I receive the error:

```
Loading required package: S4Vectors
Error in .requirePackage(package) : 
  unable to find required package ‘S4Vectors’
In addition: Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘S4Vectors’
```

I was able to install manually by using:
```
install.packages("BiocManager")
BiocManager::install("S4Vectors")
```

However it would be nice if it were installed automatically when you install dsExposomeClient

**Comment by ESCRI11** [comment]
fixed on [6ababe9](https://github.com/isglobal-brge/dsExposomeClient/commit/6ababe9ee70b4edaab6ca23e4738acdfbc86e709)
